version: '3'

services:
  portfolio-backend:
    image: maxlehmann01/git-custom-badges:latest
    container_name: git-custom-badges
    ports:
      - "3010:3000"
    restart: always
    volumes:
      - ~/deployment/git-custom-badges/.env:/usr/src/app/.env
      - ~/deployment/git-custom-badges/logs/:/usr/src/app/logs
    environment:
      - TZ=Europe/Berlin